document.write('axsldsrj <br/>');
a=10;
b="10";
document.write(typeof(a));
document.write(typeof(b));
document.write("<br> <br> " + a + b + "<br> <br>");
console.log("asfetete");
// alert("ddfg");
var accountbalance= 10000;
console.log(accountbalance);
var accountbalance=20000;
let accbal=10000;
console.log(accbal);
 accbal=20000;
 console.log(accbal);
 const pi=3.14;
 console.log(pi);
 pi=4.12;
 console.log(pi);